name: Build Gradle project
# on settings
on:
  push:
    branches:
      - master
      - main
# permissions
permissions:
  contents: write
  deployments: write
  pages: write
# jobs
jobs:
  build-gradle-project:
    runs-on: ubuntu-latest
    # job steps
    steps:
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      # check out sources
      - name: Checkout project sources
        id: checkout_project
        uses: actions/checkout@v4.1.4
      # setup jdk 17
      - name: Set up JDK 17
        id: setup_java
        uses: actions/setup-java@v4.2.1
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle
      # setup gradle
      - name: Setup Gradle
        id: setup_gradle
        uses: gradle/actions/setup-gradle@v3
      # be sure it is executable
      - name: Grant execute permission for gradlew
        id: grant_gradle
        run: chmod +x gradlew
      # build packages for release
      - name: Build Release
        id: build_release
        run: ./gradlew --stacktrace clean createPackages
      # generate version number to env
      - name: Prepare Version Number
        id: prepare_version
        run: |
          export APP_VERSION=$(date '+%Y-%m-%d');
          echo "GITHUB_APP_VERSION_NAME=$(echo $APP_VERSION)" >> $GITHUB_ENV
      # publish package release
      - name: Create Release
        id: release
        uses: ncipollo/release-action@v1.14.0
        with:
          name: Release v ${{ env.GITHUB_APP_VERSION_NAME }}
          allowUpdates: true
          token: ${{ secrets.TOKEN }}
          tag: release-${{ env.GITHUB_APP_VERSION_NAME }}
          artifacts: './packages/main/dev/*'
      - uses: actions/cache@v2
        with:
          key: ${{ github.ref }}
          path: .cache
      #      - run: pip install mkdocs-material
      #      - run: pip install mkdocs-glightbox
      #      - run: mkdocs gh-deploy --force
      # update wiki pages
#      - name: Update wiki pages
#        id: update_wiki_pages
#        run: chmod a+x ./scripts/update-wiki.sh && ./scripts/update-wiki.sh
#        shell: bash
#        env:
#            WIKI_DIR: './documentation'
#            GH_TOKEN: ${{ secrets.TOKEN }}
# done